# Init db:
#
# docker compose exec fdb bash -c "fdbcli --exec 'configure new single ssd-redwood-1'"
# docker compose exec fdb bash -c "fdbcli --exec 'status'"

# env:
#
# FDB_CLUSTER_FILE

services:
    fdb:
        image: foundationdb/foundationdb:7.3.59
        restart: always
        ports:
            - "4500:4500"
        container_name: fdb
        # FoundationDB requires CAP_SYS_NICE for priority-based processes
        cap_add:
            - SYS_NICE
        volumes:
            - fdb-data:/var/fdb/data
    
    fdb_backup_agent:
        image: foundationdb/foundationdb:7.3.59
        restart: always
        depends_on:
            - fdb
        volumes:
            - ./backups:/backups
        container_name: fdb_backup_agent
        entrypoint:
            - /usr/bin/tini
            - -g
            - --
            - bash
            - -c
            - |
                echo docker:docker@fdb:4500 > /var/fdb/fdb.cluster && 
                /usr/bin/backup_agent --log -C /var/fdb/fdb.cluster --knob_http_verbose_level=4 --knob_http_request_aws_v4_header=true

volumes:
    fdb-data:
