# restore process
# connect to the host, then run the following commands in sequence:
#
# cd ~/compose/fdb
# aws s3 sync s3://bridgex-foundationdb-backups ./backups-tmp/
# sudo mv /backups-tmp/* ./backups
# docker exec -it fdb fdbcli --exec "writemode on; clearrange \x00 \xff"
# docker exec -it fdb_backup_agent fdbrestore start -r file:///backups/backup-<latest_backup> --dest-cluster-file /var/fdb/fdb.cluster -w

on:
  schedule:
    - cron: 0 4 * * *
  workflow_dispatch:

name: Backup fdb

jobs:
  deploy:
    name: Backup fdb
    runs-on: ubuntu-latest

    steps:
      - name: Backup fdb
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: phoenix.bridgex.dev
          username: chad
          key: ${{ secrets.MOONLORD_KEY }}
          port: 22
          script_stop: true
          script: |
            cd ~/stacks/fdb
            docker compose exec -it fdb fdbbackup start -d file:///backups -w
            aws s3 sync ./backups s3://bridgex-foundationdb-backups/
            sudo rm -rf ./backups/*
